name: tests

on:
  push:
    branches:
      - "*"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cache Nix
        uses: cachix/cachix-action@v7
        with:
          name: martinbaillie
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Fix macOS Environment
        if: runner.os == 'macOS'
        # https://github.com/NixOS/nixpkgs/issues/71625
        run: nix-env -iA bashInteractive -f '<nixpkgs>'
      - name: Acceptance Test
        run: nix-shell --pure --run "make clean acceptance"
